-- MySQL Script generated by MySQL Workbench
-- Sun Nov 15 21:40:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pet_shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pet_shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pet_shop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pet_shop` ;

-- -----------------------------------------------------
-- Table `pet_shop`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop`.`pets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name_pet` VARCHAR(32) NULL DEFAULT NULL,
  `kind` VARCHAR(32) NULL DEFAULT NULL,
  `breed` CHAR(64) NULL DEFAULT NULL,
  `coulor` CHAR(32) NULL DEFAULT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pet_shop`.`pets_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pet_shop`.`pets_info` (
  `id_pets` INT(11) NOT NULL,
  `age` INT(2) NULL DEFAULT NULL,
  `char_pet` VARCHAR(32) NULL DEFAULT NULL,
  `photo` BLOB NULL DEFAULT NULL,
  `chip` INT(20) NULL DEFAULT NULL,
  INDEX `id_idx` (`id_pets` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`id_pets`)
    REFERENCES `pet_shop`.`pets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
